@echo off
python -m venv venv
echo Creating virtual environment...

call venv\Scripts\activate.bat
echo Activating virtual environment...

pip install -r requirements.txt
echo Installing dependencies...

echo Starting FastAPI application...
uvicorn app:app --reload --host 0.0.0.0 --port 8000 