@echo off
echo Creating virtual environment...
python -m venv streamlit_env

echo Activating virtual environment...
call streamlit_env\Scripts\activate.bat

echo Installing dependencies...
pip install -r requirements.txt

echo Starting Streamlit app...
streamlit run streamlit_app.py 